[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "eff5c798800d0a2ec968020def0ec2fa35dc827d"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "961d7e7748fc7bd0cdd828722c2232f8cfb74f4e1073200fff7321c074b68218"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.0.1/vegaliteassets-3.0.1-i686-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "843a6b1fc78d9ef8301eb3c376f4bbba2fa6612f"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "8955a9f82d984c4d94615c809762ae3d3d0b32c4358193365de0148a251ca4d2"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.0.1/vegaliteassets-3.0.1-x86_64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "10358abda0881fdcc0f02b086ed3f8826bf62d77"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "ad1a64e13e73a83717ff5e32ed2d588ce560004fa9c48942c3c5657c5518cc77"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.0.1/vegaliteassets-3.0.1-aarch64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "cdb4de1d477dc08af964f9ffa37a175a36b7bc60"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "6db1c06b46546c8ede256c0eb83d2b8ebb02c3464cf5f2e343ecee90f920cf23"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.0.1/vegaliteassets-3.0.1-arm-linux-gnueabihf.tar.gz"
[[vegalite_app]]
arch = "powerpc64le"
git-tree-sha1 = "eef3d725a8df665a1f46072a584c1589347a9ece"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "5833f0fb29a2918094e7569718c72c6380241d9995cd01081f652255a96d810f"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.0.1/vegaliteassets-3.0.1-powerpc64le-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "50eb47b939e5422109e057fcab6aa6507b51b23e"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "26a4654f622375205872f397bebdc6768fc6b3e735ec5d496c8ec49650e23ebe"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.0.1/vegaliteassets-3.0.1-i686-linux-musl.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "300842c8de492d73da1734850025e60b49057c52"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "fc1a295b5674f13bddea0d376909a741b64f0bb3d96dcc2c2f30359a944ea5d9"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.0.1/vegaliteassets-3.0.1-x86_64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "f0f9b680a29699f17a0240f1b61dc382000ddeec"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "e27d54e099fb7e878fbcc7f80e8dcbb769ba401efdf6654a0d47e8418d51cb7d"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.0.1/vegaliteassets-3.0.1-aarch64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "f47820717ed1b50641f69b508b903893dee34b6b"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "20db6c202284ea56bb426cc14648166ee36dd95388766076000da05e6d2d92f7"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.0.1/vegaliteassets-3.0.1-arm-linux-musleabihf.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "f1355c3a7341e9caf02def5881625f8fa52ef990"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "98fa265b57fa207f34d1419bd9923ada550add146134b5becf77a5c644b61d6a"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.0.1/vegaliteassets-3.0.1-x86_64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "1c74ca51933dc5aff771d1d364767a624d945a94"
os = "freebsd"

    [[vegalite_app.download]]
    sha256 = "8ef9634ae3414428b835c0babb6dd0b1963af7e7c003fd07240efc1bc8d1ac04"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.0.1/vegaliteassets-3.0.1-x86_64-unknown-freebsd11.1.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "5fa97953634df4052418e515ad96a1db6e006ae5"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "1557f73f230c92d5949285fe4a73d3aaeb0736205a754a5559d4cde2f7ea8749"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.0.1/vegaliteassets-3.0.1-i686-w64-mingw32.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "6c0d20011a134f5b2bd2d0266be6ffd42b8817d8"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "34057aa3b9a1102025c89a389bd71b710ad6c468010e90d28d5dd56328cd974a"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v3.0.1/vegaliteassets-3.0.1-x86_64-w64-mingw32.tar.gz"
